# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'RealmSwift', '~>10'
target 'MyDailyLife' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyDailyLife

  target 'MyDailyLifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyDailyLifeUITests' do
    # Pods for testing
  end

end
